### ISSUE TITLE
Hover issue

### ISSUE THREAD

**Issue by russmaxdesign** [fixel99/tesla#1]
@fixel99 There seems to be as hover issue. When you roll over the side nav, the entire body drops in opacity. This is very disconcerting - I presume not deliberate?

**Comment by fixel99** [comment]
I was testing something, but it should have been commented out for now. Not sure why it does it on your end?

**Comment by russmaxdesign** [comment]
This is the problem:

```css
.container-fluid > div {
  -webkit-transition:0.5s;
  transition:0.5s;
  opacity:0.6;
}

.container-fluid:hover > div {
  opacity: 0.6;
}

.container-fluid > div:hover {
  opacity: 1;
}
```

I would remove this chunk of code as it is very confusing and the rules actually clash. Plus it gives a weird effect.
