### ISSUE TITLE
Some elements load after fade in

### ISSUE THREAD

**Issue by fixel99** [fixel99/tesla#15]
@russmaxdesign As of the latest commit of #14 I have added a fade in (This was supposed to be a seperate branch but I screwed up). While I like the look of this, on the sidebar the text and triangle load in after the fade finishes. It also moves the background about a milimetre to the left (However I'm not so concerned about this). I'm not sure why this is. Any Ideas? (BTW the fade in is located in the last lines of the CSS file)

**Comment by russmaxdesign** [comment]
Are you sure it is the last line? I'm getting the following as the last CSS ruleset:

```css
/* Google Map embed responsive */
iframe, object, embed {
    max-width: 100%;
}
```

**Comment by fixel99** [comment]
@russmaxdesign Sorry it was the last line at time of commit but had changed since then. Fade is currently on line 287:

```css
.tesla-panel {

    -webkit-animation: fadein 1.5s; /* Safari, Chrome and Opera > 12.1 */
       -moz-animation: fadein 1.5s; /* Firefox < 16 */
        -ms-animation: fadein 1.5s; /* Internet Explorer */
         -o-animation: fadein 1.5s; /* Opera < 12.1 */
            animation: fadein 1.5s;
}

@keyframes fadein {
    from { opacity: 0.3; }
    to   { opacity: 1; }
}

/* Firefox < 16 */
@-moz-keyframes fadein {
    from { opacity: 0.3; }
    to   { opacity: 1; }
}

/* Safari, Chrome and Opera > 12.1 */
@-webkit-keyframes fadein {
    from { opacity: 0.3; }
    to   { opacity: 1; }
}

/* Internet Explorer */
@-ms-keyframes fadein {
    from { opacity: 0.3; }
    to   { opacity: 1; }
}

/* Opera < 12.1 */
@-o-keyframes fadein {
    from { opacity: 0.3; }
    to   { opacity: 1; }
}
```
