### ISSUE TITLE
Question, do you like position-attachment: fixed?

### ISSUE THREAD

**Issue by russmaxdesign** [fixel99/tesla#2]
@fixel99, Try adding a declaration on your local version and see if you like it. The declaration is:

```css
  background-attachment: fixed;
```

It goes into the following rule:

```css
.tesla-panel {
  height: 100vh;
  background-position: center;
  background-size: cover;
  background-attachment: fixed;
  padding-top: 10vh;
}
```

This sets the background images to a fixed position so that they do not scroll with the page. You may like it or hate it. Up to you :)
